old = hookmetamethod(game, "__namecall", function(self, ...)
if getnamecallmethod() == "InvokeServer" and self.Name == "UpdateDamageKey" then
   a = {...}
   getgenv().damageid = a[1]
end
return old(self, ...)
end)


local DamageKey;

DamageKey = game:GetService("ReplicatedStorage").UpdateDamageKey

local recoilremote;

local function bringzombies()
	for i,v in pairs(getgenv().ZombiesGroup:GetChildren()) do
		if v:FindFirstChild("HumanoidRootPart") then
			v.HumanoidRootPart.CFrame = game.Players.LocalPlayer.Character:WaitForChild("HumanoidRootPart").CFrame + game.Players.LocalPlayer.Character:WaitForChild("HumanoidRootPart").CFrame.LookVector * 10;
		end
	end
end

local function godmode()
	if (game:GetService("UserInputService"):IsKeyDown(Enum.KeyCode.F)) then
	
	else
		lastpos = game.Players.LocalPlayer.Character:WaitForChild("HumanoidRootPart").CFrame
		game.Workspace.Camera.CameraType = "Fixed";
		game.Players.LocalPlayer.Character:WaitForChild("HumanoidRootPart").CFrame = game.Players.LocalPlayer.Character:WaitForChild("HumanoidRootPart").CFrame+Vector3.new(0,100,0)
		wait()
		game.Players.LocalPlayer.Character:WaitForChild("HumanoidRootPart").CFrame = lastpos+Vector3.new(0,-0.48,0)
		game.Workspace.Camera.CameraType = "Custom";
	end
	local lastpos;

end

local function hyperguns()

if (game.Players.LocalPlayer.Character:FindFirstChild("RotCam")) then
	recoilremote = game.Players.LocalPlayer.Character.RotCam;
	recoilremote.Parent = nil
end
if (game:GetService("Players").LocalPlayer.PlayerGui.HUD:FindFirstChild("UpdateAmmo")) then
		-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

	game:GetService("Players").LocalPlayer.PlayerGui.HUD.UpdateAmmo:Fire()
end
if (game:GetService("Players").LocalPlayer.PlayerScripts:FindFirstChild("Knife")) then
	local m1 = require(game:GetService("Players").LocalPlayer.PlayerScripts.Knife)
end

if (game:GetService("Players").LocalPlayer.Backpack:FindFirstChild("Weapon1")) then
	local m1 = require(game:GetService("Players").LocalPlayer.Backpack.Weapon1)
	m1.AimTime = 0.12

	m1.MoveSpeed = 5

	m1.MagSize = 9999

	m1.Semi = false

	m1.AimFOV = 120

	m1.Spread.Min = 0
	m1.Spread.Max = 0

	m1.Ammo = 9999

	m1.FireTime = 0.01
	
	m1.TorsoShot = 99999
	
	m1.HeadShot = 999999

	m1.MaxAmmo = 9999
	
	m1.LimbShot = 99999
	
	m1.AimSpread = 0

end

if (game:GetService("Players").LocalPlayer.Backpack:FindFirstChild("Weapon2")) then
	local m2 = require(game:GetService("Players").LocalPlayer.Backpack.Weapon2)
	m2.AimTime = 0.12

	m2.MoveSpeed = 5
	
	m2.LimbShot = 99999
	
	m2.FireTime = 0.01

	m2.MagSize = 9999
	
	m2.AimSpread = 0

	m2.Semi = false

	m2.AimFOV = 120

	m2.TorsoShot = 99999
	
	m2.HeadShot = 999999
	
	m2.Spread.Min = 0
	m2.Spread.Max = 0

	m2.Ammo = 9999

	m2.MaxAmmo = 9999
end

end

local function repairallbaricaddes()

	for i,v in pairs(workspace.Interact:GetChildren()) do
		if v.Name == "Barricade" then
		
			local ohInstance1 = game.Players.LocalPlayer.Character:WaitForChild("Interact").OnKeyUp
			local ohNumber2 = 1

			v.Activate:FireServer(ohInstance1, ohNumber2)
			wait(0.01)
			
		end
	end

end

local function killallzombies()
	if (workspace.Baddies:FindFirstChild("Zombie")) then
		for i,v in pairs(workspace.Baddies:GetChildren()) do
				

			local mouse = game.Players.LocalPlayer:GetMouse();

			local ohTable1 = {
				["BodyPart"] = v.Torso,
				["Force"] = 10000,
				["GibPower"] = 10000,
				["Damage"] = math.huge
			}
			local ohNumber2 = getgenv().damageid;
			v.Humanoid.Damage:FireServer(ohTable1, ohNumber2)
		end	
	end

end

getgenv().mousekillkey = Enum.KeyCode.E;
local function mousekillszombies()
		-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

	local mouse = game.Players.LocalPlayer:GetMouse();
	
	if (game:GetService("UserInputService"):IsKeyDown(Enum.KeyCode.E)) then
		if (mouse.Target.Parent.Name == "Zombie") then
			local ohTable1 = {
				["BodyPart"] = mouse.Target,
				["Force"] =10000,
				["GibPower"] = 10000,
				["Damage"] = math.huge
			}
			local ohNumber2 = getgenv().damageid;

			mouse.Target.Parent.Humanoid.Damage:FireServer(ohTable1, ohNumber2)
		end	
	end




end

getgenv().protectionaura = 5

local function zombiekillaura(player)
	for i,v in pairs(workspace.Baddies:GetChildren()) do
		if (v:FindFirstChild("HumanoidRootPart")) then
			if (game.Players:FindFirstChild(tostring(player)).Character:FindFirstChild("HumanoidRootPart")) then
				if ((game.Players[getgenv().protecttarget].Character:FindFirstChild("HumanoidRootPart").Position - v.HumanoidRootPart.Position).magnitude < getgenv().protectionaura) then
					local ohTable1 = {
						["BodyPart"] = v.HumanoidRootPart,
						["Force"] = 10000,
						["GibPower"] = 10000,
						["Damage"] = math.huge
					}
					local ohNumber2 = getgenv().damageid

					v.Humanoid.Damage:FireServer(ohTable1, ohNumber2)					
				end
			end
		end
	end
end

local function getmoney(amount)
	for i =1,amount do
		-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

		local mouse = game.Players.LocalPlayer:GetMouse();

		local ohTable1 = {
			["BodyPart"] = mouse.Target,
			["Force"] = 0,
			["GibPower"] = 1,
			["Damage"] = 0
		}
		local ohNumber2 = getgenv().damageid;

		workspace.Baddies.Zombie.Humanoid.Damage:FireServer(ohTable1, ohNumber2)
	end
end

local function anchorzombies()

end

local function unanchorzombies()

end



local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()

local Window = Library.CreateLib("Sleepy Hub", "DarkTheme")

getgenv().ZombiesGroup = game:GetService("Workspace").Baddies

local PlayerTab = Window:NewTab('Player')
local CombatTab = Window:NewTab("Combat")
local ClientTab = Window:NewTab("Client")
local ExploitsTab = Window:NewTab("Exploits")
local SettingsTab = Window:NewTab("Settings")






local PlayerSection = PlayerTab:NewSection('Player')
local CombatSection = CombatTab:NewSection("Combat")
local ClientSection = ClientTab:NewSection("Client")
local ExploitsSection = ExploitsTab:NewSection("Exploits")
local SettingsSection = SettingsTab:NewSection('KeyBinds')











SettingsSection:NewKeybind("Toggle Gui", "Toggles the gui", Enum.KeyCode.RightControl, function()
	Library:ToggleUI()
end)


local test = false

CombatSection:NewToggle('Bring All Zombies','',function(Testing)
    
    test = Testing
    
    if test == true then
        
        repeat wait()            
            
			bringzombies();
			
            until test == false
			unanchorzombies();
        end
    
    
end)
 
local test = false

CombatSection:NewToggle('Hyper Mod Guns','',function(Testing)
    
    test = Testing
    
    if test == true then
        
        repeat wait()            
            
			hyperguns();
			
            until test == false
			unanchorzombies();
			recoilremote.Parent = game.Players.LocalPlayer.Character
			
        end
    
    
end)

CombatSection:NewTextBox("Set Spread For Weapons","",function(value)
	if (game:GetService("Players").LocalPlayer.Backpack:FindFirstChild("Weapon1")) then
		local m1 = require(game:GetService("Players").LocalPlayer.Backpack.Weapon1)
		m1.Spread.Min = value
		m1.Spread.Max = value
	end

	if (game:GetService("Players").LocalPlayer.Backpack:FindFirstChild("Weapon2")) then
		local m2 = require(game:GetService("Players").LocalPlayer.Backpack.Weapon2)
		m2.Spread.Min = value
		m2.Spread.Max = value
	end

end)
 
local test = false

ExploitsSection:NewToggle('Repair Barricades Aura ','',function(Testing)
    
    test = Testing
    
    if test == true then
        
        repeat wait()            
            
			repairallbaricaddes();
			
            until test == false
			
        end
    
    
end)
 
ExploitsSection:NewTextBox("Get money : ","",function(amount)
	pcall(function()
		getmoney(amount);
	end)
	
end)
local test1 = false

ExploitsSection:NewToggle('Loop Kill All Zombies','',function(Testing)
    
    test1 = Testing
    
    if test1 == true then
        
        repeat wait()            
            killallzombies();			
        until test1 == false
    end
    
    
end)



ExploitsSection:NewButton("Kill all Zombies","",killallzombies)
 
local test = false
   
PlayerSection:NewToggle('Godmode','',function(Testing)
    
    test = Testing
    
    if test == true then
        
        repeat wait()            
            
			godmode();
			
            until test == false
			
        end
    
    
 end)
 
local test = false

CombatSection:NewToggle('Mouse Kill Zombies (Button in Settings)','',function(Testing)
    
    test = Testing
    
    if test == true then
        
        repeat wait()            
            
			mousekillszombies();
			
            until test == false
        end
    
    
end)


CombatSection:NewTextBox("Set Killaura for player","",function(target)
	for i,v in pairs(game.Players:GetPlayers()) do
		if string.find(v.Name, tostring(target)) then
			print(v.Name);
			getgenv().protecttarget = v.Name;
			getgenv().protecttargetchar = v;
		end
	end
end)

CombatSection:NewTextBox("Set Kill Aura Range","",function(range)
	getgenv().protectionaura = tonumber(range)
end)

local test = false

CombatSection:NewToggle('Activate Killaura for player','',function(Testing)
    
    test = Testing
    
    if test == true then
        
        repeat wait()            
            
			zombiekillaura(getgenv().protecttarget)
			
            until test == false
        end
    
    
end)
